services:
  litetask:
    build: .
    image: ghcr.io/georgijgrigoriev/litetask:v0.0.1
    ports:
      - "8080:8080"
    environment:
      AUTH_SECRET: "change-me-32-bytes-min"
      ALLOW_REGISTRATION: "true"
      DB_PATH: "/data/tasks.db"
      PORT: "8080"
    volumes:
      - litetask-data:/data

volumes:
  litetask-data:

# Alternatively if you dont like to use docker volumes, you
# can use a bind mount instead:
#    volumes:
#      - ./data:/data
